### ISSUE TITLE
JMeter Test fails with memory-usage:url=app.funnyapps.com\:11188

### ISSUE THREAD

**Issue by leiferksn** [undera/perfmon-agent#14]
When trying to collect some metrics through JMX, I get the following exception

java.lang.RuntimeException: Invalid metric specified: jmx

Caused by: java.lang.RuntimeException: Couldn't get metrics from: [class kg.apc.perfmon.metrics.PerfMonMetricsCreatorImpl]
	at kg.apc.perfmon.metrics.PerfMonMetricsService.getMetric(PerfMonMetricsService.java:51)
	at kg.apc.perfmon.metrics.AbstractPerfMonMetric.createMetric(AbstractPerfMonMetric.java:48)
	... 18 more

I use custom url for JMX memory-usage:url=app.funnyapps.com\:11188 and the example from the readme. I can reproduce the problem when I run the test 

AbstractPerfMonMetricTest.testCreateMetric() with the following settings

        String metricType = "jmx";
        String metricParams = "memory-usage:url=app.funntapps.de\\:11188";

**Comment by leiferksn** [comment]
By setting the url first I was able to see the metric.

"url=app.funntapps.de\\:11188:memory-usage"
