### ISSUE TITLE
The server cannot be started normally under MAC arm64 architecture

### ISSUE THREAD

**Issue by Murphy-hub** [undera/perfmon-agent#25]
```shell
zhangshuai@zhangshuaideMacBook-Pro-2  ~/Downloads/ServerAgent-2.2.1  ./startAgent.sh                                                     
0 [main] DEBUG Sigar  - Can't load library: /Users/zhangshuai/Downloads/ServerAgent-2.2.1/lib/libsigar-universal64-macosx.dylib
org.hyperic.sigar.SigarException: Can't load library: /Users/zhangshuai/Downloads/ServerAgent-2.2.1/lib/libsigar-universal64-macosx.dylib
	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
	at kg.apc.perfmon.PerfMonWorker.<init>(PerfMonWorker.java:54)
	at kg.apc.perfmon.AgentTool.getWorker(AgentTool.java:90)
	at kg.apc.perfmon.AgentTool.processParams(AgentTool.java:23)
	at kg.apc.cmdtools.PluginsCMD.processParams(PluginsCMD.java:63)
	at kg.apc.cmdtools.PluginsCMD.processParams(PluginsCMD.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at kg.apc.cmd.UniversalRunner.main(UniversalRunner.java:175)
INFO    2022-07-02 12:11:26.882 [kg.apc.p] (): Binding UDP to 4444
INFO    2022-07-02 12:11:26.906 [kg.apc.p] (): Binding TCP to 4444
INFO    2022-07-02 12:11:26.907 [kg.apc.p] (): JP@GC Agent v2.2.0 started
```

**Comment by undera** [comment]
The underlying SIGAR library were built at the times when modern Macs did not exist. We can't do much about it, sorry.
