### ISSUE TITLE
Error getting metric

### ISSUE THREAD

**Issue by MentosL** [undera/perfmon-agent#31]
When I tried to get cpu and memory indicators, I found that I couldn't get them

environment：
Apple M1 Pro
macos ：ventura 13.4 (22F66)
jdk  17

```java
INFO    2023-06-20 10:13:05.108 [kg.apc.p] (): Accepting new TCP connection
INFO    2023-06-20 10:13:05.112 [kg.apc.p] (): Yep, we received the 'test' command
INFO    2023-06-20 10:13:05.113 [kg.apc.p] (): Starting measures: disks i/o:	cpu:	memory:
WARN    2023-06-20 10:13:05.121 [kg.apc.p] (): Can't get filesystems map
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Sigar.getFileSystemListNative()[Lorg/hyperic/sigar/FileSystem;
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getFileSystemMap(Unknown Source)
	at kg.apc.perfmon.metrics.DiskIOMetric.getAllDiskFilesystems(DiskIOMetric.java:64)
	at kg.apc.perfmon.metrics.DiskIOMetric.<init>(DiskIOMetric.java:55)
	at kg.apc.perfmon.metrics.PerfMonMetricsCreatorImpl.getMetricProvider(PerfMonMetricsCreatorImpl.java:28)
	at kg.apc.perfmon.metrics.PerfMonMetricsService.getMetric(PerfMonMetricsService.java:35)
	at kg.apc.perfmon.metrics.AbstractPerfMonMetric.createMetric(AbstractPerfMonMetric.java:48)
	at kg.apc.perfmon.PerfMonMetricGetter.setUpMetrics(PerfMonMetricGetter.java:137)
	at kg.apc.perfmon.PerfMonMetricGetter.processCommand(PerfMonMetricGetter.java:61)
	at kg.apc.perfmon.PerfMonMetricGetter.processNextCommand(PerfMonMetricGetter.java:100)
	at kg.apc.perfmon.PerfMonWorker.read(PerfMonWorker.java:198)
	at kg.apc.perfmon.PerfMonWorker.processCommands(PerfMonWorker.java:87)
	at kg.apc.perfmon.AgentTool.processParams(AgentTool.java:75)
	at kg.apc.cmdtools.PluginsCMD.processParams(PluginsCMD.java:63)
	at kg.apc.cmdtools.PluginsCMD.processParams(PluginsCMD.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kg.apc.cmd.UniversalRunner.main(UniversalRunner.java:174)
ERROR   2023-06-20 10:13:05.505 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getCpuPerc(Unknown Source)
	at kg.apc.perfmon.metrics.CPUTotalMetric.getValue(CPUTotalMetric.java:60)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:05.505 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getMem(Unknown Source)
	at kg.apc.perfmon.metrics.MemTotalMetric.getValue(MemTotalMetric.java:41)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:06.508 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getCpuPerc(Unknown Source)
	at kg.apc.perfmon.metrics.CPUTotalMetric.getValue(CPUTotalMetric.java:60)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:06.509 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getMem(Unknown Source)
	at kg.apc.perfmon.metrics.MemTotalMetric.getValue(MemTotalMetric.java:41)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:07.510 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getCpuPerc(Unknown Source)
	at kg.apc.perfmon.metrics.CPUTotalMetric.getValue(CPUTotalMetric.java:60)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:07.510 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getMem(Unknown Source)
	at kg.apc.perfmon.metrics.MemTotalMetric.getValue(MemTotalMetric.java:41)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:08.513 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getCpuPerc(Unknown Source)
	at kg.apc.perfmon.metrics.CPUTotalMetric.getValue(CPUTotalMetric.java:60)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:08.514 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getMem(Unknown Source)
	at kg.apc.perfmon.metrics.MemTotalMetric.getValue(MemTotalMetric.java:41)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:09.518 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getCpuPerc(Unknown Source)
	at kg.apc.perfmon.metrics.CPUTotalMetric.getValue(CPUTotalMetric.java:60)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:09.519 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getMem(Unknown Source)
	at kg.apc.perfmon.metrics.MemTotalMetric.getValue(MemTotalMetric.java:41)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:10.524 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getCpuPerc(Unknown Source)
	at kg.apc.perfmon.metrics.CPUTotalMetric.getValue(CPUTotalMetric.java:60)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:10.525 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getMem(Unknown Source)
	at kg.apc.perfmon.metrics.MemTotalMetric.getValue(MemTotalMetric.java:41)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:11.529 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getCpuPerc(Unknown Source)
	at kg.apc.perfmon.metrics.CPUTotalMetric.getValue(CPUTotalMetric.java:60)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:11.530 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getMem(Unknown Source)
	at kg.apc.perfmon.metrics.MemTotalMetric.getValue(MemTotalMetric.java:41)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:12.533 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getCpuPerc(Unknown Source)
	at kg.apc.perfmon.metrics.CPUTotalMetric.getValue(CPUTotalMetric.java:60)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:12.535 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getMem(Unknown Source)
	at kg.apc.perfmon.metrics.MemTotalMetric.getValue(MemTotalMetric.java:41)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:13.538 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getCpuPerc(Unknown Source)
	at kg.apc.perfmon.metrics.CPUTotalMetric.getValue(CPUTotalMetric.java:60)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:13.539 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getMem(Unknown Source)
	at kg.apc.perfmon.metrics.MemTotalMetric.getValue(MemTotalMetric.java:41)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:14.543 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getCpuPerc(Unknown Source)
	at kg.apc.perfmon.metrics.CPUTotalMetric.getValue(CPUTotalMetric.java:60)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:14.544 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getMem(Unknown Source)
	at kg.apc.perfmon.metrics.MemTotalMetric.getValue(MemTotalMetric.java:41)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:15.547 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Cpu.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getCpuPerc(Unknown Source)
	at kg.apc.perfmon.metrics.CPUTotalMetric.getValue(CPUTotalMetric.java:60)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)
ERROR   2023-06-20 10:13:15.549 [kg.apc.p] (): Error getting metric
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Mem.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at com.sun.proxy.$Proxy0.getMem(Unknown Source)
	at kg.apc.perfmon.metrics.MemTotalMetric.getValue(MemTotalMetric.java:41)
	at kg.apc.perfmon.PerfMonMetricGetter.getMetricsLine(PerfMonMetricGetter.java:113)
	at kg.apc.perfmon.PerfMonWorker.processSenders(PerfMonWorker.java:268)
	at kg.apc.perfmon.PerfMonWorker.run(PerfMonWorker.java:231)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by undera** [comment]
Perfmon agent relies on [SIGAR library](https://github.com/hyperic/sigar), that were last updated long before M1 was invented. We can't do much with it here.

**Comment by MentosL** [comment]
> Perfmon agent relies on [SIGAR library](https://github.com/hyperic/sigar), that were last updated long before M1 was invented. We can't do much with it here.

Thank you for your reply, so currently I have no way to get collection information on m1 is it

**Comment by undera** [comment]
With this agent - no. In today's world, the approach to collect metrics became totally different. It uses other agents that push metrics to some database, from where you access it via dashboard.
