### ISSUE TITLE
Plugin does not run on JMeter 3.2

### ISSUE THREAD

**Issue by devptrz** [undera/perfmon-agent#5]
Does not work when running on JMeter 3.2. Per [this SO response](https://stackoverflow.com/questions/44866784/perfmon-metrics-collector-error), JMeter 3.2 has removed the setFormatter function. Exception in JMeter log is:

```
2017-09-20 20:00:01,423 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.NoSuchMethodError: org.apache.jmeter.samplers.SampleSaveConfiguration.setFormatter(Ljava/text/DateFormat;)V
	at kg.apc.jmeter.JMeterPluginsUtils.doBestCSVSetup(JMeterPluginsUtils.java:256) ~[jmeter-plugins-cmn-jmeter-0.3.jar:?]
	at kg.apc.jmeter.perfmon.PerfMonCollector.setupSaving(PerfMonCollector.java:136) ~[jmeter-plugins-perfmon-2.1.jar:?]
	at kg.apc.jmeter.perfmon.PerfMonCollector.testStarted(PerfMonCollector.java:113) ~[jmeter-plugins-perfmon-2.1.jar:?]
	at org.apache.jmeter.reporters.ResultCollector.testStarted(ResultCollector.java:355) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at kg.apc.jmeter.vizualizers.CorrectedResultCollector.testStarted(CorrectedResultCollector.java:28) ~[jmeter-plugins-cmn-jmeter-0.3.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:218) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:388) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by undera** [comment]
This issue has nothing to do with PerfMon agent, JMeterPluginsUtils is not agent's code. Ask on jmeter plugins support forums.
